version: 2

sphinx:
  configuration: docs/sources/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements/doc-requirements.txt
    - requirements: requirements/requirements.txt
