[tool.black]
line-length = 88
target-version = ['py36','py37']
include = '\.pyi?$'
exclude = '''
(
  /(
     \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.nox
    | \.venv
    | buck-out
    | build
    | dist
    | pai/libs/*
   )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["pai", "tests"]
#known_first_party = ["pai", "tests"]

[tool.pytest.ini_options]
timeout = 600

[doc8]
max-line-length=88
verbose=1
