name: Publish Package
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAI_PYPI_TOKEN: ${{ secrets.PAI_PYPI_TOKEN }}
      ALIPAI_PYPI_TOKEN: ${{ secrets.ALIPAI_PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install wheel setuptools twine
      # build and upload package pai
      - name: Build package for pai
        run: python setup.py sdist bdist_wheel
      - name: Publish package to PyPI (pai)
        run: twine upload dist/* --skip-existing -u __token__ -p $PAI_PYPI_TOKEN
      - name: cleanup
        run: |
          rm -rf dist
          rm -rf build
          rm -rf pai.egg-info
      # build and upload package alipai
      - name: Build package for alipai
        run: PACKAGE_NAME=alipai python setup.py sdist bdist_wheel
      - name: Publish package to PyPI (alipai)
        run: twine upload dist/* --skip-existing -u __token__ -p $ALIPAI_PYPI_TOKEN
